import "./styles.css";
import { changeTitle } from "./ts/changeTitle";
import { displayTasks } from "./ts/displayTasks";
// import { createTask } from "./ts/createTask";
// import { createPara } from "./ts/script";
// createPara();
changeTitle();
displayTasks();
// createTask();
console.log("hello world");
